### ISSUE TITLE
없는 검색 keyword 에러 처리

### ISSUE THREAD

**Issue by dev-LeoKang** [r4576/ReagentPlatform#16]
잘못 입력한 검색어에 대한 에러 처리가 필요할 것 같습니다.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/38308646/109011441-377d7a00-76f4-11eb-985d-44b988433487.png">

예시로, get_Table_data 함수에 argument를 wat를 주었을 때의 에러 문구입니다.

**Comment by r4576** [comment]
![image](https://user-images.githubusercontent.com/77832848/109149004-576f7500-77aa-11eb-9f92-8b9877b88f8d.png)
['wat']을 return하도록 설정했습니다

**Comment by dev-LeoKang** [comment]
혹시, get_Table_data 함수에서 데이터가 없는 물질명이 입력 되었을 경우에 None 값이 return이 되도록 할 수 있을까요?
Backend 에도 잘못 입력한 물질명 데이터가 있어서, Frontend에 "사용자가 검색한 물질명 중에 무엇이 잘못된 것인지"를 전달하는 것은 문제 없을 것 같습니다.
